/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package WDC.ui;

import WDC.interfaces.Calculations;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 * 
 * @author ARMIGER1
 * @version 1.0
 */
public class MainFrame extends javax.swing.JFrame implements Calculations {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    // Global variables
    
    /**
     * Formats a decimal to three (3) decimal places.
     */
    DecimalFormat threeDigits = new DecimalFormat("0.000");
    
    /**
     * Formats a decimal to one (1) decimal place.
     */
    DecimalFormat oneDigit = new DecimalFormat("0.0");
    
    /**
     * Signals that the process is ready to execute.
     * If true, process is ready, else process is not ready.
     */
    boolean readyFlag = false;
    
    /**
     * Converts a pixel value into ems
     * 
     * @param baseSize double The base size in pixels
     * @param desiredSize double The desired size, also in pixels
     * @return The converted size in ems
     */
    @Override
    public double px_to_em(double baseSize, double desiredSize) {
        double result;
        
        result = desiredSize / baseSize;
        
        return result;
    }
    
    /**
     * Converts a pixel value into a percent.
     * 
     * @param baseSize double The base size in pixels
     * @param desiredSize double The desired size, also in pixels
     * @return The converted size as a percent
     * @see MainFrame#px_to_em(double, double)
     */
    @Override
    public double px_to_percent(double baseSize, double desiredSize) {
        double result;
        
        result = (desiredSize / baseSize) * 100;
        
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_base_size = new javax.swing.JLabel();
        lbl_desired_size = new javax.swing.JLabel();
        lbl_result = new javax.swing.JLabel();
        tf_base_size = new javax.swing.JTextField();
        tf_desired_size = new javax.swing.JTextField();
        tf_result = new javax.swing.JTextField();
        cb_unit = new javax.swing.JComboBox();
        btn_convert = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Web Design Unit Converter");
        setResizable(false);

        lbl_base_size.setText("Base Font Size (px):");

        lbl_desired_size.setText("Desired Font Size (px):");

        lbl_result.setText("Result:");

        tf_base_size.setToolTipText("Enter your base font size in pixels here.");

        tf_desired_size.setToolTipText("<html> Enter the size you want to convert to in pixels. <br /> <br /> For example, if your base font size is 10px and you want to resize it to 42px, enter '42' (without the quotes). </html>");

        tf_result.setEditable(false);
        tf_result.setToolTipText("Here's your completed conversion in the units you specified with the drop-down menu to the right.");

        cb_unit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EM", "%" }));

        btn_convert.setText("Convert!");
        btn_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset Fields");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(btn_convert, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lbl_desired_size)
                            .add(lbl_base_size)
                            .add(lbl_result))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tf_base_size, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tf_desired_size, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(tf_result, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cb_unit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(btn_reset, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbl_base_size)
                    .add(tf_base_size, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbl_desired_size)
                    .add(tf_desired_size, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbl_result)
                    .add(tf_result, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cb_unit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn_convert)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn_reset)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertActionPerformed
        
        // Make sure that both fields are filled and consist ONLY of numbers and maybe a decimal.
        if (tf_base_size.getText().matches(REGEX) && tf_desired_size.getText().matches(REGEX) && (!"".equals(tf_base_size.getText()) && !"".equals(tf_desired_size.getText()) ) ) {
            readyFlag = true;
        } else {
            readyFlag = false;
        }
        
        if (readyFlag == true) {
            double base = Double.parseDouble(tf_base_size.getText());
            double target = Double.parseDouble(tf_desired_size.getText());
            double answer = 0;
            
            switch (cb_unit.getSelectedIndex()) {
                case UNIT_EM:
                    answer = px_to_em(base, target);
                    answer = Double.parseDouble(threeDigits.format(answer));
                    break;
                case UNIT_PERCENT:
                    answer = px_to_percent(base, target);
                    answer = Double.parseDouble(oneDigit.format(answer));
                    break;
            }
            
            tf_result.setText(Double.toString(answer));
            
        } else {
            //JOptionPane.showConfirmDialog(null, "Please enter a number for your base size and desired size.", "Error!", WIDTH);
            JOptionPane.showConfirmDialog(null, "Please enter a number for your base and desired sizes.", "Error!", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_convertActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        tf_base_size.setText("");
        tf_desired_size.setText("");
        tf_result.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_convert;
    private javax.swing.JButton btn_reset;
    private javax.swing.JComboBox cb_unit;
    private javax.swing.JLabel lbl_base_size;
    private javax.swing.JLabel lbl_desired_size;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JTextField tf_base_size;
    private javax.swing.JTextField tf_desired_size;
    private javax.swing.JTextField tf_result;
    // End of variables declaration//GEN-END:variables
}
